/* generated by unplugin-react-components */
export {}
declare global{
	const LazyLoad: typeof import('./src/utils/LazyLoad')['default']
	const NotFound: typeof import('./src/view/404')['default']
	const I18n: typeof import('./src/components/LangSelect/index')['default']
	const Theme: typeof import('./src/components/Theme/index')['default']
	const UserAvater: typeof import('./src/components/UserAvater/index')['default']
	const Logo: typeof import('./src/layout/components/Logo')['default']
	const TabsTop: typeof import('./src/layout/components/TabsTop')['default']
}